apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: youtube-clone-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
    - name: youtube-clone.rules
      rules:
        - alert: HighCPUUsage
          expr: (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m]))) * 100 > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "CPU usage trên 80%"

        - alert: PodCrashLooping
          expr: increase(kube_pod_container_status_restarts_total{namespace="application"}[1h]) > 3
          for: 10m
          labels:
            severity: critical
          annotations:
            summary: "Pod {{ $labels.pod }} đang crash loop"

        - alert: HighMemoryUsage
          expr: (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) * 100 > 85
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Memory usage trên 85%"
